### PR TITLE
RawHTMLBlock and QuoteBlock

### PR DESCRIPTION
**Pull request by MiltonLn**
Uncommenting compressor due to errors on entry page

Adding a solution to the visualisation of tables in entry pages because they are not displaying with css styling, please take a look to the puput.js file and tell me if this is a right solution.

Trying a solution to the bad display of richtext blocks this was proposed by Marc Tudurí but is not working, i didn't know if i didn't test it right

This is the error:
image

### CODE REVIEW

**Comment by MiltonLn** [comment]
This is how the tables display solution looks:

image

**Comment by MiltonLn** [comment]
Any feedback here?

**Comment by MiltonLn** [comment]
Hello Tim,

It seems that your problem with the panels was the `EntryAbstract`'s `content_panels` attribute, when that attribute is called, it is taking the `main_panels` value from `EntryAbstract` instead of `StreamEntryPage`, my solution (violating the DRY pattern :( ) was to override the `content_panels` value directly on `StreamEntryPage` and now it takes properly the right `main_panels` value, i could not think of a better solution.

Please tell me what do you think of it and if you are ok with this we can go ahead.

**Comment by FlipperPA** [comment]
Hi Milton, the code looks good, but the issue we might want to  discuss the issue with other Puput users. Part of the reason for this StreamField work on my part was specifically to keep end users from doing things like using Raw HTML. Over the years, I've seen far too much content from WYSIWYGs and short cuts using HTML that ends up being a huge amount of technical debt. That said, that's just my preference. I think we should bring this up on Puput's issue and see what the creator thinks. I'm fine if this goes in the direction you're headed if the Puput community agrees, I may just head in another direction if that's the case. :) I'll make a comment on the PR and we can see where it goes.

**Comment by MiltonLn** [comment]
PR Updated, RawHTML removed.

**Pull request merged**
